spring.config.activate.on-profile=qa
app.env=QA
logging.level.org.springframework.boot.context.config=DEBUG

account.name=kartik lohate (QA)
account.detail.address=bhopal MP
account.detail.current=gurgaon
account.detail.env=QA
account.contact=8800990088, 8899887722

spring.application.name=redis_app
spring.data.redis.host=localhost
spring.data.redis.port=6379