spring.config.activate.on-profile=prod
app.env=POD
logging.level.org.springframework.boot.context.config=DEBUG

account.name=kartik lohate (PROD123)
account.detail.address={cipher}581cfe0f452feb082f206ec8bba6a29f90dc81a2038633e962bc0661311e443b
account.detail.current=gurgaon
account.detail.env=PROD
account.contact=8800990088, 7415950037

spring.application.name=redis_app
spring.data.redis.host=localhost
spring.data.redis.port=6379
