spring.config.activate.on-profile=dev
app.env=DEV
logging.level.org.springframework.boot.context.config=DEBUG

account.name=kartik lohate (DEV)
account.detail.address=bhopal MP
account.detail.current=gurgaon
account.detail.env=DEV
account.contact=8800990088, 8899887722

spring.application.name=redis_app
spring.data.redis.host=localhosts
spring.data.redis.port=6379