spring.config.activate.on-profile=prod
app.env=POD
logging.level.org.springframework.boot.context.config=DEBUG

account.name=kartik lohate (PROD)
account.detail.address=bhopal MP
account.detail.current=gurgaon
account.detail.env=PROD
account.contact=8800990088, 7415950037

spring.application.name=redis_app
spring.data.redis.host=localhost
spring.data.redis.port=6379